### ISSUE TITLE
Gnome 40 don't like gconftool command

### ISSUE THREAD

**Issue by gicrisf** [denysdovhan/one-gnome-terminal#11]
I tried installing on a fresh Arch installation with Gnome 40 but the script try to launch `gconftool` commands that simply cannot be found on the system. I think it's a compatibility problem with Gnome 40. 
I solved copypasting the colors manually in the GUI for a new custom profile, but I'm opening this issue as early advice for the future.

Thanks for your work

**Comment by denysdovhan** [comment]
I don't use gnome anymore. I'll be grateful if you can add any notice in readme about it.
