### ISSUE TITLE
Nothing changed after installation.

### ISSUE THREAD

**Issue by csrgxtu** [denysdovhan/one-gnome-terminal#2]
i am using ubuntu gnome 14.04, and use following command

``` bash
wget https://raw.githubusercontent.com/denysdovhan/gnome-terminal-one/master/one-dark.sh && . one-dark.sh
```

nothing changed

**Comment by denysdovhan** [comment]
Sure, because this command only installs color profile into gnome-terminal. You have to switch to this color profile in your terminal settings.

**Comment by AlynxZhou** [comment]
@denysdovhan I think you should use `&& . ./one-dark.sh` to replace `&& . one-dark.sh`, as for my zsh this works.

**Comment by baskoroi** [comment]
I basically closed and reopened my terminal. That also worked. (Running on Ubuntu 20.04)
