### ISSUE TITLE
Not working on Linux Mint 18

### ISSUE THREAD

**Issue by miroslavvidovic** [denysdovhan/one-gnome-terminal#4]
I followed the installation instructions and nothing happened. The terminal doesn't close after install and I can't select the One Dark theme. My OS is Linux Mint 18.

**Comment by miroslavvidovic** [comment]
I had to install dconf-cli first. Now the theme is working. My bad.

**Comment by denysdovhan** [comment]
Okay, things happen ¯_(ツ)_/¯
