### ISSUE TITLE
gconftool: command not found on Gnome 3.22.2

### ISSUE THREAD

**Issue by a118n** [denysdovhan/one-gnome-terminal#6]
After executing script:
./one-dark.sh: line 109: gconftool: command not found
./one-dark.sh: line 109: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found
./one-dark.sh: line 93: gconftool: command not found

Arch Linux, Gnome 3.22.2

It seems it uses "Fallback for Gnome 2 and early Gnome 3" for some reason..

**Comment by a118n** [comment]
Nevermind, I figured it out.

**Comment by denysdovhan** [comment]
@a118n have you missed to install gconftool?

**Comment by a118n** [comment]
I don't think I need gconftool on Gnome 3.22, it supposed to use dconf. Just my $PATH was all empty for some reason, it couldn't find the dconf bin and thus reverting to gconftool which it couldn't find either.

**Comment by huchiwen** [comment]
I have same problem,can you tell me how to resolve?

**Comment by MauriceWebb** [comment]
> Nevermind, I figured it out.

It would be helpful to post what the solution was!

**Comment by kinowarrior** [comment]
Agree.

**Comment by A-L-Fearon** [comment]
Checking "Run command as login shell" option in the gnome-terminal preferences fixed the issue for me.

**Comment by A-L-Fearon** [comment]
Checking "Run command as a login shell" option in the gnome-terminal preferences fixed the issue for me.
